name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          sleep 10 && exit 0
      - name: Dispatch Build Success
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: jonoliver/actions
          event-type: build-success
