name: Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          exit 0
      - name: Dispatch Build Success
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: jonoliver/actions
          event-type: build-success
