name: Manual

on:
  push:
    branches:
      - 'main'
      - 'test2'
  workflow_dispatch:
jobs:
  manual:
    runs-on: ubuntu-18.04
    steps:
      - name: Manual
        run: |
          echo ${github.ref}
          echo ${github.sha}
